### ISSUE TITLE
如果需要再次确认输入的密码怎么办呢?

### ISSUE THREAD

**Issue by zhongzilu** [superSp/PasswordInputEdt#1]
哥，现在有个需求，就是需要再次确认输入的密码，该项目好像没有实现。另外，需要暴露一个清空输入内容的接口

**Comment by superSp** [comment]
> 哥，现在有个需求，就是需要再次确认输入的密码，该项目好像没有实现。另外，需要暴露一个清空输入内容的接口

已经加上啦
